//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Plus54PortfolioRedesign2014.Resources.resources.global
{
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Global_res
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Global_res()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.resources.global.Global_res", typeof(Global_res).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string BackButton
        {
            get
            {
                return ResourceManager.GetString("BackButton", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CancelButton
        {
            get
            {
                return ResourceManager.GetString("CancelButton", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Clear All Values.
        /// </summary>
        public static string ClearAllValues_Link
        {
            get
            {
                return ResourceManager.GetString("ClearAllValues_Link", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string CloseButton
        {
            get
            {
                return ResourceManager.GetString("CloseButton", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        public static string ColumnHeader_Actions
        {
            get
            {
                return ResourceManager.GetString("ColumnHeader_Actions", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Is Enabled.
        /// </summary>
        public static string ColumnHeader_IsEnable
        {
            get
            {
                return ResourceManager.GetString("ColumnHeader_IsEnable", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string ConfirmButton
        {
            get
            {
                return ResourceManager.GetString("ConfirmButton", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Confirm Delete.
        /// </summary>
        public static string ConfirmDeleteButton
        {
            get
            {
                return ResourceManager.GetString("ConfirmDeleteButton", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Confirm Export.
        /// </summary>
        public static string ConfirmExportButton
        {
            get
            {
                return ResourceManager.GetString("ConfirmExportButton", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The selected item could not be found..
        /// </summary>
        public static string CouldNotBeFoundErrorText
        {
            get
            {
                return ResourceManager.GetString("CouldNotBeFoundErrorText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Add New.
        /// </summary>
        public static string CreateNew_Link
        {
            get
            {
                return ResourceManager.GetString("CreateNew_Link", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Delete All Selected.
        /// </summary>
        public static string DeleteAllSelectedButton
        {
            get
            {
                return ResourceManager.GetString("DeleteAllSelectedButton", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string DeleteButton
        {
            get
            {
                return ResourceManager.GetString("DeleteButton", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Delete selected.
        /// </summary>
        public static string DeleteSelectedButton
        {
            get
            {
                return ResourceManager.GetString("DeleteSelectedButton", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Details_Link
        {
            get
            {
                return ResourceManager.GetString("Details_Link", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        public static string DoneButton
        {
            get
            {
                return ResourceManager.GetString("DoneButton", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string Download_Link
        {
            get
            {
                return ResourceManager.GetString("Download_Link", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Select one.
        /// </summary>
        public static string DropDownText
        {
            get
            {
                return ResourceManager.GetString("DropDownText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Duplicate.
        /// </summary>
        public static string DuplicateButton
        {
            get
            {
                return ResourceManager.GetString("DuplicateButton", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit_Link
        {
            get
            {
                return ResourceManager.GetString("Edit_Link", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        public static string Export_Link
        {
            get
            {
                return ResourceManager.GetString("Export_Link", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        public static string ExportButton
        {
            get
            {
                return ResourceManager.GetString("ExportButton", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to File Not Found.
        /// </summary>
        public static string FileNotFoundErrorText
        {
            get
            {
                return ResourceManager.GetString("FileNotFoundErrorText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        public static string Import_Link
        {
            get
            {
                return ResourceManager.GetString("Import_Link", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ...loading....
        /// </summary>
        public static string LoadingText
        {
            get
            {
                return ResourceManager.GetString("LoadingText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string OkButton
        {
            get
            {
                return ResourceManager.GetString("OkButton", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The file that you are attempting to download not exists..
        /// </summary>
        public static string PopupFileNotFound_Text
        {
            get
            {
                return ResourceManager.GetString("PopupFileNotFound_Text", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to File Not Found.
        /// </summary>
        public static string PopupFileNotFound_Title
        {
            get
            {
                return ResourceManager.GetString("PopupFileNotFound_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Publish.
        /// </summary>
        public static string Publish_Link
        {
            get
            {
                return ResourceManager.GetString("Publish_Link", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string SaveButton
        {
            get
            {
                return ResourceManager.GetString("SaveButton", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Save Info.
        /// </summary>
        public static string SaveInfoButton
        {
            get
            {
                return ResourceManager.GetString("SaveInfoButton", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string Select_Link
        {
            get
            {
                return ResourceManager.GetString("Select_Link", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Select/Unselect all.
        /// </summary>
        public static string SelectUnselectAll
        {
            get
            {
                return ResourceManager.GetString("SelectUnselectAll", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string SendButton
        {
            get
            {
                return ResourceManager.GetString("SendButton", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} was created Successfully..
        /// </summary>
        public static string SuccessCreateGeneric
        {
            get
            {
                return ResourceManager.GetString("SuccessCreateGeneric", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} was updated Successfully..
        /// </summary>
        public static string SuccessEditGeneric
        {
            get
            {
                return ResourceManager.GetString("SuccessEditGeneric", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Unknown error (Exception)..
        /// </summary>
        public static string UnknownErrorExceptionText
        {
            get
            {
                return ResourceManager.GetString("UnknownErrorExceptionText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Unknown error..
        /// </summary>
        public static string UnkownErrorText
        {
            get
            {
                return ResourceManager.GetString("UnkownErrorText", resourceCulture);
            }
        }
    }
}
