//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Plus54PortfolioRedesign2014.Resources.resources.global
{
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Import_res
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Import_res()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.resources.global.Import_res", typeof(Import_res).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Click Here.
        /// </summary>
        public static string DownloadExampleLink
        {
            get
            {
                return ResourceManager.GetString("DownloadExampleLink", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Download sample spreadsheet.
        /// </summary>
        public static string DownloadExampleMessage
        {
            get
            {
                return ResourceManager.GetString("DownloadExampleMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Download log.
        /// </summary>
        public static string DownloadLogLink
        {
            get
            {
                return ResourceManager.GetString("DownloadLogLink", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Import Process Finished: {0}&lt;br/&gt;.
        /// </summary>
        public static string FinishedImportProcess
        {
            get
            {
                return ResourceManager.GetString("FinishedImportProcess", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Upload Finished: Status: {0}.
        /// </summary>
        public static string FinishedStatus
        {
            get
            {
                return ResourceManager.GetString("FinishedStatus", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to A General Error has occurred: {0}&lt;br/&gt;.
        /// </summary>
        public static string GeneralErrorInfo
        {
            get
            {
                return ResourceManager.GetString("GeneralErrorInfo", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Error at Row {0} : {1}.
        /// </summary>
        public static string HeaderErrorRow
        {
            get
            {
                return ResourceManager.GetString("HeaderErrorRow", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to More Details: {0}&lt;br/&gt;.
        /// </summary>
        public static string MoreInfo
        {
            get
            {
                return ResourceManager.GetString("MoreInfo", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Processing Row: {0}&lt;br/&gt;.
        /// </summary>
        public static string ProcessingRowInfo
        {
            get
            {
                return ResourceManager.GetString("ProcessingRowInfo", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Error occurred at Row: {0}&lt;br/&gt;: {1}&lt;br/&gt;.
        /// </summary>
        public static string RowErrorInfo
        {
            get
            {
                return ResourceManager.GetString("RowErrorInfo", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Starting Import Process: {0}&lt;br/&gt;.
        /// </summary>
        public static string StartImportProcess
        {
            get
            {
                return ResourceManager.GetString("StartImportProcess", resourceCulture);
            }
        }
    }
}
