//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("Plus54PortfolioRedesign2014Model", "FK_Project_Thumbnail", "Project", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Plus54PortfolioRedesign2014.Entities.Project), "PortfolioImage", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Plus54PortfolioRedesign2014.Entities.PortfolioImage))]
[assembly: EdmRelationshipAttribute("Plus54PortfolioRedesign2014Model", "FK_Project_SliderImages", "Project", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Plus54PortfolioRedesign2014.Entities.Project), "PortfolioImage", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Plus54PortfolioRedesign2014.Entities.PortfolioImage))]
[assembly: EdmRelationshipAttribute("Plus54PortfolioRedesign2014Model", "FK_Project_Client", "Project", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Plus54PortfolioRedesign2014.Entities.Project), "Client", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Plus54PortfolioRedesign2014.Entities.Client))]
[assembly: EdmRelationshipAttribute("Plus54PortfolioRedesign2014Model", "FK_Project_Partner", "Project", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Plus54PortfolioRedesign2014.Entities.Project), "Partner", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Plus54PortfolioRedesign2014.Entities.Partner))]
[assembly: EdmRelationshipAttribute("Plus54PortfolioRedesign2014Model", "FK_Technology_Thumbnail", "Technology", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Plus54PortfolioRedesign2014.Entities.Technology), "PortfolioImage", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Plus54PortfolioRedesign2014.Entities.PortfolioImage))]
[assembly: EdmRelationshipAttribute("Plus54PortfolioRedesign2014Model", "FK_SocialMedia_Thumbnail", "SocialMedia", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Plus54PortfolioRedesign2014.Entities.SocialMedia), "PortfolioImage", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Plus54PortfolioRedesign2014.Entities.PortfolioImage))]
[assembly: EdmRelationshipAttribute("Plus54PortfolioRedesign2014Model", "FK_ProjectCategory_Thumbnail", "ProjectCategory", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Plus54PortfolioRedesign2014.Entities.ProjectCategory), "PortfolioImage", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Plus54PortfolioRedesign2014.Entities.PortfolioImage))]
[assembly: EdmRelationshipAttribute("Plus54PortfolioRedesign2014Model", "FK_Project_Technologies", "Project", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Plus54PortfolioRedesign2014.Entities.Project), "Technology", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Plus54PortfolioRedesign2014.Entities.Technology))]
[assembly: EdmRelationshipAttribute("Plus54PortfolioRedesign2014Model", "FK_Project_SocialMedia", "Project", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Plus54PortfolioRedesign2014.Entities.Project), "SocialMedia", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Plus54PortfolioRedesign2014.Entities.SocialMedia))]
[assembly: EdmRelationshipAttribute("Plus54PortfolioRedesign2014Model", "FK_Project_ProjectTypeTag", "Project", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Plus54PortfolioRedesign2014.Entities.Project), "ProjectTypeTag", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Plus54PortfolioRedesign2014.Entities.ProjectTypeTag))]
[assembly: EdmRelationshipAttribute("Plus54PortfolioRedesign2014Model", "FK_Project_SiteLogo", "Project", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Plus54PortfolioRedesign2014.Entities.Project), "PortfolioImage", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Plus54PortfolioRedesign2014.Entities.PortfolioImage))]
[assembly: EdmRelationshipAttribute("Plus54PortfolioRedesign2014Model", "FK_Project_ProjectCategory", "Project", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Plus54PortfolioRedesign2014.Entities.Project), "ProjectCategory", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Plus54PortfolioRedesign2014.Entities.ProjectCategory))]
[assembly: EdmRelationshipAttribute("Plus54PortfolioRedesign2014Model", "FK_ScreenSupport_Thumbnail", "ScreenSupport", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Plus54PortfolioRedesign2014.Entities.ScreenSupport), "PortfolioImage", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Plus54PortfolioRedesign2014.Entities.PortfolioImage))]
[assembly: EdmRelationshipAttribute("Plus54PortfolioRedesign2014Model", "FK_Project_ScreenSupport", "Project", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Plus54PortfolioRedesign2014.Entities.Project), "ScreenSupport", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Plus54PortfolioRedesign2014.Entities.ScreenSupport))]

#endregion

namespace Plus54PortfolioRedesign2014.Entities
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class Plus54PortfolioRedesign2014Entities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new Plus54PortfolioRedesign2014Entities object using the connection string found in the 'Plus54PortfolioRedesign2014Entities' section of the application configuration file.
        /// </summary>
        public Plus54PortfolioRedesign2014Entities() : base("name=Plus54PortfolioRedesign2014Entities", "Plus54PortfolioRedesign2014Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new Plus54PortfolioRedesign2014Entities object.
        /// </summary>
        public Plus54PortfolioRedesign2014Entities(string connectionString) : base(connectionString, "Plus54PortfolioRedesign2014Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new Plus54PortfolioRedesign2014Entities object.
        /// </summary>
        public Plus54PortfolioRedesign2014Entities(EntityConnection connection) : base(connection, "Plus54PortfolioRedesign2014Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<PortfolioImage> PortfolioImage
        {
            get
            {
                if ((_PortfolioImage == null))
                {
                    _PortfolioImage = base.CreateObjectSet<PortfolioImage>("PortfolioImage");
                }
                return _PortfolioImage;
            }
        }
        private ObjectSet<PortfolioImage> _PortfolioImage;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Project> Project
        {
            get
            {
                if ((_Project == null))
                {
                    _Project = base.CreateObjectSet<Project>("Project");
                }
                return _Project;
            }
        }
        private ObjectSet<Project> _Project;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Client> Client
        {
            get
            {
                if ((_Client == null))
                {
                    _Client = base.CreateObjectSet<Client>("Client");
                }
                return _Client;
            }
        }
        private ObjectSet<Client> _Client;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Partner> Partner
        {
            get
            {
                if ((_Partner == null))
                {
                    _Partner = base.CreateObjectSet<Partner>("Partner");
                }
                return _Partner;
            }
        }
        private ObjectSet<Partner> _Partner;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Technology> Technology
        {
            get
            {
                if ((_Technology == null))
                {
                    _Technology = base.CreateObjectSet<Technology>("Technology");
                }
                return _Technology;
            }
        }
        private ObjectSet<Technology> _Technology;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<SocialMedia> SocialMedia
        {
            get
            {
                if ((_SocialMedia == null))
                {
                    _SocialMedia = base.CreateObjectSet<SocialMedia>("SocialMedia");
                }
                return _SocialMedia;
            }
        }
        private ObjectSet<SocialMedia> _SocialMedia;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ProjectCategory> ProjectCategory
        {
            get
            {
                if ((_ProjectCategory == null))
                {
                    _ProjectCategory = base.CreateObjectSet<ProjectCategory>("ProjectCategory");
                }
                return _ProjectCategory;
            }
        }
        private ObjectSet<ProjectCategory> _ProjectCategory;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ProjectTypeTag> ProjectTypeTag
        {
            get
            {
                if ((_ProjectTypeTag == null))
                {
                    _ProjectTypeTag = base.CreateObjectSet<ProjectTypeTag>("ProjectTypeTag");
                }
                return _ProjectTypeTag;
            }
        }
        private ObjectSet<ProjectTypeTag> _ProjectTypeTag;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ScreenSupport> ScreenSupport
        {
            get
            {
                if ((_ScreenSupport == null))
                {
                    _ScreenSupport = base.CreateObjectSet<ScreenSupport>("ScreenSupport");
                }
                return _ScreenSupport;
            }
        }
        private ObjectSet<ScreenSupport> _ScreenSupport;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the PortfolioImage EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPortfolioImage(PortfolioImage portfolioImage)
        {
            base.AddObject("PortfolioImage", portfolioImage);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Project EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToProject(Project project)
        {
            base.AddObject("Project", project);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Client EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToClient(Client client)
        {
            base.AddObject("Client", client);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Partner EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPartner(Partner partner)
        {
            base.AddObject("Partner", partner);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Technology EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTechnology(Technology technology)
        {
            base.AddObject("Technology", technology);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the SocialMedia EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSocialMedia(SocialMedia socialMedia)
        {
            base.AddObject("SocialMedia", socialMedia);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ProjectCategory EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToProjectCategory(ProjectCategory projectCategory)
        {
            base.AddObject("ProjectCategory", projectCategory);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ProjectTypeTag EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToProjectTypeTag(ProjectTypeTag projectTypeTag)
        {
            base.AddObject("ProjectTypeTag", projectTypeTag);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ScreenSupport EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToScreenSupport(ScreenSupport screenSupport)
        {
            base.AddObject("ScreenSupport", screenSupport);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Plus54PortfolioRedesign2014Model", Name="Client")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Client : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Client object.
        /// </summary>
        /// <param name="idClient">Initial value of the IdClient property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        public static Client CreateClient(global::System.Int32 idClient, global::System.String name)
        {
            Client client = new Client();
            client.IdClient = idClient;
            client.Name = name;
            return client;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdClient
        {
            get
            {
                return _IdClient;
            }
            set
            {
                if (_IdClient != value)
                {
                    OnIdClientChanging(value);
                    ReportPropertyChanging("IdClient");
                    _IdClient = StructuralObject.SetValidValue(value, "IdClient");
                    ReportPropertyChanged("IdClient");
                    OnIdClientChanged();
                }
            }
        }
        private global::System.Int32 _IdClient;
        partial void OnIdClientChanging(global::System.Int32 value);
        partial void OnIdClientChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false, "Name");
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Plus54PortfolioRedesign2014Model", "FK_Project_Client", "Project")]
        public EntityCollection<Project> Projects
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Project>("Plus54PortfolioRedesign2014Model.FK_Project_Client", "Project");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Project>("Plus54PortfolioRedesign2014Model.FK_Project_Client", "Project", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Plus54PortfolioRedesign2014Model", Name="Partner")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Partner : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Partner object.
        /// </summary>
        /// <param name="idPartner">Initial value of the IdPartner property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        public static Partner CreatePartner(global::System.Int32 idPartner, global::System.String name)
        {
            Partner partner = new Partner();
            partner.IdPartner = idPartner;
            partner.Name = name;
            return partner;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdPartner
        {
            get
            {
                return _IdPartner;
            }
            set
            {
                if (_IdPartner != value)
                {
                    OnIdPartnerChanging(value);
                    ReportPropertyChanging("IdPartner");
                    _IdPartner = StructuralObject.SetValidValue(value, "IdPartner");
                    ReportPropertyChanged("IdPartner");
                    OnIdPartnerChanged();
                }
            }
        }
        private global::System.Int32 _IdPartner;
        partial void OnIdPartnerChanging(global::System.Int32 value);
        partial void OnIdPartnerChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false, "Name");
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Plus54PortfolioRedesign2014Model", "FK_Project_Partner", "Project")]
        public EntityCollection<Project> Projects
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Project>("Plus54PortfolioRedesign2014Model.FK_Project_Partner", "Project");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Project>("Plus54PortfolioRedesign2014Model.FK_Project_Partner", "Project", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Plus54PortfolioRedesign2014Model", Name="PortfolioImage")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class PortfolioImage : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new PortfolioImage object.
        /// </summary>
        /// <param name="idImage">Initial value of the IdImage property.</param>
        /// <param name="path">Initial value of the Path property.</param>
        /// <param name="type">Initial value of the Type property.</param>
        /// <param name="height">Initial value of the Height property.</param>
        /// <param name="width">Initial value of the Width property.</param>
        public static PortfolioImage CreatePortfolioImage(global::System.Int32 idImage, global::System.String path, global::System.String type, global::System.Int32 height, global::System.Int32 width)
        {
            PortfolioImage portfolioImage = new PortfolioImage();
            portfolioImage.IdImage = idImage;
            portfolioImage.Path = path;
            portfolioImage.Type = type;
            portfolioImage.Height = height;
            portfolioImage.Width = width;
            return portfolioImage;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdImage
        {
            get
            {
                return _IdImage;
            }
            set
            {
                if (_IdImage != value)
                {
                    OnIdImageChanging(value);
                    ReportPropertyChanging("IdImage");
                    _IdImage = StructuralObject.SetValidValue(value, "IdImage");
                    ReportPropertyChanged("IdImage");
                    OnIdImageChanged();
                }
            }
        }
        private global::System.Int32 _IdImage;
        partial void OnIdImageChanging(global::System.Int32 value);
        partial void OnIdImageChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Path
        {
            get
            {
                return _Path;
            }
            set
            {
                OnPathChanging(value);
                ReportPropertyChanging("Path");
                _Path = StructuralObject.SetValidValue(value, false, "Path");
                ReportPropertyChanged("Path");
                OnPathChanged();
            }
        }
        private global::System.String _Path;
        partial void OnPathChanging(global::System.String value);
        partial void OnPathChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Type
        {
            get
            {
                return _Type;
            }
            set
            {
                OnTypeChanging(value);
                ReportPropertyChanging("Type");
                _Type = StructuralObject.SetValidValue(value, false, "Type");
                ReportPropertyChanged("Type");
                OnTypeChanged();
            }
        }
        private global::System.String _Type;
        partial void OnTypeChanging(global::System.String value);
        partial void OnTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Height
        {
            get
            {
                return _Height;
            }
            set
            {
                OnHeightChanging(value);
                ReportPropertyChanging("Height");
                _Height = StructuralObject.SetValidValue(value, "Height");
                ReportPropertyChanged("Height");
                OnHeightChanged();
            }
        }
        private global::System.Int32 _Height;
        partial void OnHeightChanging(global::System.Int32 value);
        partial void OnHeightChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Width
        {
            get
            {
                return _Width;
            }
            set
            {
                OnWidthChanging(value);
                ReportPropertyChanging("Width");
                _Width = StructuralObject.SetValidValue(value, "Width");
                ReportPropertyChanged("Width");
                OnWidthChanged();
            }
        }
        private global::System.Int32 _Width;
        partial void OnWidthChanging(global::System.Int32 value);
        partial void OnWidthChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Plus54PortfolioRedesign2014Model", Name="Project")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Project : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Project object.
        /// </summary>
        /// <param name="idProject">Initial value of the IdProject property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="overview">Initial value of the Overview property.</param>
        /// <param name="year">Initial value of the Year property.</param>
        /// <param name="createdDate">Initial value of the CreatedDate property.</param>
        public static Project CreateProject(global::System.Int32 idProject, global::System.String name, global::System.String overview, global::System.Int32 year, global::System.DateTime createdDate)
        {
            Project project = new Project();
            project.IdProject = idProject;
            project.Name = name;
            project.Overview = overview;
            project.Year = year;
            project.CreatedDate = createdDate;
            return project;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdProject
        {
            get
            {
                return _IdProject;
            }
            set
            {
                if (_IdProject != value)
                {
                    OnIdProjectChanging(value);
                    ReportPropertyChanging("IdProject");
                    _IdProject = StructuralObject.SetValidValue(value, "IdProject");
                    ReportPropertyChanged("IdProject");
                    OnIdProjectChanged();
                }
            }
        }
        private global::System.Int32 _IdProject;
        partial void OnIdProjectChanging(global::System.Int32 value);
        partial void OnIdProjectChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false, "Name");
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Overview
        {
            get
            {
                return _Overview;
            }
            set
            {
                OnOverviewChanging(value);
                ReportPropertyChanging("Overview");
                _Overview = StructuralObject.SetValidValue(value, false, "Overview");
                ReportPropertyChanged("Overview");
                OnOverviewChanged();
            }
        }
        private global::System.String _Overview;
        partial void OnOverviewChanging(global::System.String value);
        partial void OnOverviewChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Url
        {
            get
            {
                return _Url;
            }
            set
            {
                OnUrlChanging(value);
                ReportPropertyChanging("Url");
                _Url = StructuralObject.SetValidValue(value, true, "Url");
                ReportPropertyChanged("Url");
                OnUrlChanged();
            }
        }
        private global::System.String _Url;
        partial void OnUrlChanging(global::System.String value);
        partial void OnUrlChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Year
        {
            get
            {
                return _Year;
            }
            set
            {
                OnYearChanging(value);
                ReportPropertyChanging("Year");
                _Year = StructuralObject.SetValidValue(value, "Year");
                ReportPropertyChanged("Year");
                OnYearChanged();
            }
        }
        private global::System.Int32 _Year;
        partial void OnYearChanging(global::System.Int32 value);
        partial void OnYearChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime CreatedDate
        {
            get
            {
                return _CreatedDate;
            }
            set
            {
                OnCreatedDateChanging(value);
                ReportPropertyChanging("CreatedDate");
                _CreatedDate = StructuralObject.SetValidValue(value, "CreatedDate");
                ReportPropertyChanged("CreatedDate");
                OnCreatedDateChanged();
            }
        }
        private global::System.DateTime _CreatedDate;
        partial void OnCreatedDateChanging(global::System.DateTime value);
        partial void OnCreatedDateChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Plus54PortfolioRedesign2014Model", "FK_Project_Thumbnail", "PortfolioImage")]
        public PortfolioImage Thumbnail
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<PortfolioImage>("Plus54PortfolioRedesign2014Model.FK_Project_Thumbnail", "PortfolioImage").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<PortfolioImage>("Plus54PortfolioRedesign2014Model.FK_Project_Thumbnail", "PortfolioImage").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<PortfolioImage> ThumbnailReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<PortfolioImage>("Plus54PortfolioRedesign2014Model.FK_Project_Thumbnail", "PortfolioImage");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<PortfolioImage>("Plus54PortfolioRedesign2014Model.FK_Project_Thumbnail", "PortfolioImage", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Plus54PortfolioRedesign2014Model", "FK_Project_SliderImages", "PortfolioImage")]
        public EntityCollection<PortfolioImage> SliderImages
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<PortfolioImage>("Plus54PortfolioRedesign2014Model.FK_Project_SliderImages", "PortfolioImage");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<PortfolioImage>("Plus54PortfolioRedesign2014Model.FK_Project_SliderImages", "PortfolioImage", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Plus54PortfolioRedesign2014Model", "FK_Project_Client", "Client")]
        public Client Client
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Client>("Plus54PortfolioRedesign2014Model.FK_Project_Client", "Client").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Client>("Plus54PortfolioRedesign2014Model.FK_Project_Client", "Client").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Client> ClientReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Client>("Plus54PortfolioRedesign2014Model.FK_Project_Client", "Client");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Client>("Plus54PortfolioRedesign2014Model.FK_Project_Client", "Client", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Plus54PortfolioRedesign2014Model", "FK_Project_Partner", "Partner")]
        public Partner Partner
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Partner>("Plus54PortfolioRedesign2014Model.FK_Project_Partner", "Partner").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Partner>("Plus54PortfolioRedesign2014Model.FK_Project_Partner", "Partner").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Partner> PartnerReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Partner>("Plus54PortfolioRedesign2014Model.FK_Project_Partner", "Partner");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Partner>("Plus54PortfolioRedesign2014Model.FK_Project_Partner", "Partner", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Plus54PortfolioRedesign2014Model", "FK_Project_Technologies", "Technology")]
        public EntityCollection<Technology> Technologies
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Technology>("Plus54PortfolioRedesign2014Model.FK_Project_Technologies", "Technology");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Technology>("Plus54PortfolioRedesign2014Model.FK_Project_Technologies", "Technology", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Plus54PortfolioRedesign2014Model", "FK_Project_SocialMedia", "SocialMedia")]
        public EntityCollection<SocialMedia> SocialMedia
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<SocialMedia>("Plus54PortfolioRedesign2014Model.FK_Project_SocialMedia", "SocialMedia");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<SocialMedia>("Plus54PortfolioRedesign2014Model.FK_Project_SocialMedia", "SocialMedia", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Plus54PortfolioRedesign2014Model", "FK_Project_ProjectTypeTag", "ProjectTypeTag")]
        public EntityCollection<ProjectTypeTag> ProjectTypeTags
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<ProjectTypeTag>("Plus54PortfolioRedesign2014Model.FK_Project_ProjectTypeTag", "ProjectTypeTag");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<ProjectTypeTag>("Plus54PortfolioRedesign2014Model.FK_Project_ProjectTypeTag", "ProjectTypeTag", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Plus54PortfolioRedesign2014Model", "FK_Project_SiteLogo", "PortfolioImage")]
        public PortfolioImage SiteLogo
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<PortfolioImage>("Plus54PortfolioRedesign2014Model.FK_Project_SiteLogo", "PortfolioImage").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<PortfolioImage>("Plus54PortfolioRedesign2014Model.FK_Project_SiteLogo", "PortfolioImage").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<PortfolioImage> SiteLogoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<PortfolioImage>("Plus54PortfolioRedesign2014Model.FK_Project_SiteLogo", "PortfolioImage");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<PortfolioImage>("Plus54PortfolioRedesign2014Model.FK_Project_SiteLogo", "PortfolioImage", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Plus54PortfolioRedesign2014Model", "FK_Project_ProjectCategory", "ProjectCategory")]
        public EntityCollection<ProjectCategory> ProjectCategory
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<ProjectCategory>("Plus54PortfolioRedesign2014Model.FK_Project_ProjectCategory", "ProjectCategory");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<ProjectCategory>("Plus54PortfolioRedesign2014Model.FK_Project_ProjectCategory", "ProjectCategory", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Plus54PortfolioRedesign2014Model", "FK_Project_ScreenSupport", "ScreenSupport")]
        public EntityCollection<ScreenSupport> ScreenSupport
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<ScreenSupport>("Plus54PortfolioRedesign2014Model.FK_Project_ScreenSupport", "ScreenSupport");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<ScreenSupport>("Plus54PortfolioRedesign2014Model.FK_Project_ScreenSupport", "ScreenSupport", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Plus54PortfolioRedesign2014Model", Name="ProjectCategory")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ProjectCategory : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ProjectCategory object.
        /// </summary>
        /// <param name="idProjectCategory">Initial value of the IdProjectCategory property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        public static ProjectCategory CreateProjectCategory(global::System.Int32 idProjectCategory, global::System.String name)
        {
            ProjectCategory projectCategory = new ProjectCategory();
            projectCategory.IdProjectCategory = idProjectCategory;
            projectCategory.Name = name;
            return projectCategory;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdProjectCategory
        {
            get
            {
                return _IdProjectCategory;
            }
            set
            {
                if (_IdProjectCategory != value)
                {
                    OnIdProjectCategoryChanging(value);
                    ReportPropertyChanging("IdProjectCategory");
                    _IdProjectCategory = StructuralObject.SetValidValue(value, "IdProjectCategory");
                    ReportPropertyChanged("IdProjectCategory");
                    OnIdProjectCategoryChanged();
                }
            }
        }
        private global::System.Int32 _IdProjectCategory;
        partial void OnIdProjectCategoryChanging(global::System.Int32 value);
        partial void OnIdProjectCategoryChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false, "Name");
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Plus54PortfolioRedesign2014Model", "FK_ProjectCategory_Thumbnail", "PortfolioImage")]
        public PortfolioImage Thumbnail
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<PortfolioImage>("Plus54PortfolioRedesign2014Model.FK_ProjectCategory_Thumbnail", "PortfolioImage").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<PortfolioImage>("Plus54PortfolioRedesign2014Model.FK_ProjectCategory_Thumbnail", "PortfolioImage").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<PortfolioImage> ThumbnailReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<PortfolioImage>("Plus54PortfolioRedesign2014Model.FK_ProjectCategory_Thumbnail", "PortfolioImage");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<PortfolioImage>("Plus54PortfolioRedesign2014Model.FK_ProjectCategory_Thumbnail", "PortfolioImage", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Plus54PortfolioRedesign2014Model", "FK_Project_ProjectCategory", "Project")]
        public EntityCollection<Project> Projects
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Project>("Plus54PortfolioRedesign2014Model.FK_Project_ProjectCategory", "Project");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Project>("Plus54PortfolioRedesign2014Model.FK_Project_ProjectCategory", "Project", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Plus54PortfolioRedesign2014Model", Name="ProjectTypeTag")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ProjectTypeTag : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ProjectTypeTag object.
        /// </summary>
        /// <param name="idProjectTypeTag">Initial value of the IdProjectTypeTag property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        public static ProjectTypeTag CreateProjectTypeTag(global::System.Int32 idProjectTypeTag, global::System.String name)
        {
            ProjectTypeTag projectTypeTag = new ProjectTypeTag();
            projectTypeTag.IdProjectTypeTag = idProjectTypeTag;
            projectTypeTag.Name = name;
            return projectTypeTag;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdProjectTypeTag
        {
            get
            {
                return _IdProjectTypeTag;
            }
            set
            {
                if (_IdProjectTypeTag != value)
                {
                    OnIdProjectTypeTagChanging(value);
                    ReportPropertyChanging("IdProjectTypeTag");
                    _IdProjectTypeTag = StructuralObject.SetValidValue(value, "IdProjectTypeTag");
                    ReportPropertyChanged("IdProjectTypeTag");
                    OnIdProjectTypeTagChanged();
                }
            }
        }
        private global::System.Int32 _IdProjectTypeTag;
        partial void OnIdProjectTypeTagChanging(global::System.Int32 value);
        partial void OnIdProjectTypeTagChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false, "Name");
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Plus54PortfolioRedesign2014Model", "FK_Project_ProjectTypeTag", "Project")]
        public EntityCollection<Project> Projects
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Project>("Plus54PortfolioRedesign2014Model.FK_Project_ProjectTypeTag", "Project");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Project>("Plus54PortfolioRedesign2014Model.FK_Project_ProjectTypeTag", "Project", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Plus54PortfolioRedesign2014Model", Name="ScreenSupport")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ScreenSupport : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ScreenSupport object.
        /// </summary>
        /// <param name="idScreenSupport">Initial value of the IdScreenSupport property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        public static ScreenSupport CreateScreenSupport(global::System.Int32 idScreenSupport, global::System.String name)
        {
            ScreenSupport screenSupport = new ScreenSupport();
            screenSupport.IdScreenSupport = idScreenSupport;
            screenSupport.Name = name;
            return screenSupport;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdScreenSupport
        {
            get
            {
                return _IdScreenSupport;
            }
            set
            {
                if (_IdScreenSupport != value)
                {
                    OnIdScreenSupportChanging(value);
                    ReportPropertyChanging("IdScreenSupport");
                    _IdScreenSupport = StructuralObject.SetValidValue(value, "IdScreenSupport");
                    ReportPropertyChanged("IdScreenSupport");
                    OnIdScreenSupportChanged();
                }
            }
        }
        private global::System.Int32 _IdScreenSupport;
        partial void OnIdScreenSupportChanging(global::System.Int32 value);
        partial void OnIdScreenSupportChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false, "Name");
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Plus54PortfolioRedesign2014Model", "FK_ScreenSupport_Thumbnail", "PortfolioImage")]
        public PortfolioImage Thumbnail
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<PortfolioImage>("Plus54PortfolioRedesign2014Model.FK_ScreenSupport_Thumbnail", "PortfolioImage").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<PortfolioImage>("Plus54PortfolioRedesign2014Model.FK_ScreenSupport_Thumbnail", "PortfolioImage").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<PortfolioImage> ThumbnailReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<PortfolioImage>("Plus54PortfolioRedesign2014Model.FK_ScreenSupport_Thumbnail", "PortfolioImage");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<PortfolioImage>("Plus54PortfolioRedesign2014Model.FK_ScreenSupport_Thumbnail", "PortfolioImage", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Plus54PortfolioRedesign2014Model", "FK_Project_ScreenSupport", "Project")]
        public EntityCollection<Project> Projects
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Project>("Plus54PortfolioRedesign2014Model.FK_Project_ScreenSupport", "Project");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Project>("Plus54PortfolioRedesign2014Model.FK_Project_ScreenSupport", "Project", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Plus54PortfolioRedesign2014Model", Name="SocialMedia")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class SocialMedia : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new SocialMedia object.
        /// </summary>
        /// <param name="idSocialMedia">Initial value of the IdSocialMedia property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        public static SocialMedia CreateSocialMedia(global::System.Int32 idSocialMedia, global::System.String name)
        {
            SocialMedia socialMedia = new SocialMedia();
            socialMedia.IdSocialMedia = idSocialMedia;
            socialMedia.Name = name;
            return socialMedia;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdSocialMedia
        {
            get
            {
                return _IdSocialMedia;
            }
            set
            {
                if (_IdSocialMedia != value)
                {
                    OnIdSocialMediaChanging(value);
                    ReportPropertyChanging("IdSocialMedia");
                    _IdSocialMedia = StructuralObject.SetValidValue(value, "IdSocialMedia");
                    ReportPropertyChanged("IdSocialMedia");
                    OnIdSocialMediaChanged();
                }
            }
        }
        private global::System.Int32 _IdSocialMedia;
        partial void OnIdSocialMediaChanging(global::System.Int32 value);
        partial void OnIdSocialMediaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false, "Name");
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Plus54PortfolioRedesign2014Model", "FK_SocialMedia_Thumbnail", "PortfolioImage")]
        public PortfolioImage Thumbnail
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<PortfolioImage>("Plus54PortfolioRedesign2014Model.FK_SocialMedia_Thumbnail", "PortfolioImage").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<PortfolioImage>("Plus54PortfolioRedesign2014Model.FK_SocialMedia_Thumbnail", "PortfolioImage").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<PortfolioImage> ThumbnailReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<PortfolioImage>("Plus54PortfolioRedesign2014Model.FK_SocialMedia_Thumbnail", "PortfolioImage");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<PortfolioImage>("Plus54PortfolioRedesign2014Model.FK_SocialMedia_Thumbnail", "PortfolioImage", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Plus54PortfolioRedesign2014Model", "FK_Project_SocialMedia", "Project")]
        public EntityCollection<Project> Projects
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Project>("Plus54PortfolioRedesign2014Model.FK_Project_SocialMedia", "Project");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Project>("Plus54PortfolioRedesign2014Model.FK_Project_SocialMedia", "Project", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Plus54PortfolioRedesign2014Model", Name="Technology")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Technology : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Technology object.
        /// </summary>
        /// <param name="idTechnology">Initial value of the IdTechnology property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        public static Technology CreateTechnology(global::System.Int32 idTechnology, global::System.String name)
        {
            Technology technology = new Technology();
            technology.IdTechnology = idTechnology;
            technology.Name = name;
            return technology;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdTechnology
        {
            get
            {
                return _IdTechnology;
            }
            set
            {
                if (_IdTechnology != value)
                {
                    OnIdTechnologyChanging(value);
                    ReportPropertyChanging("IdTechnology");
                    _IdTechnology = StructuralObject.SetValidValue(value, "IdTechnology");
                    ReportPropertyChanged("IdTechnology");
                    OnIdTechnologyChanged();
                }
            }
        }
        private global::System.Int32 _IdTechnology;
        partial void OnIdTechnologyChanging(global::System.Int32 value);
        partial void OnIdTechnologyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false, "Name");
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Plus54PortfolioRedesign2014Model", "FK_Technology_Thumbnail", "PortfolioImage")]
        public PortfolioImage Thumbnail
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<PortfolioImage>("Plus54PortfolioRedesign2014Model.FK_Technology_Thumbnail", "PortfolioImage").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<PortfolioImage>("Plus54PortfolioRedesign2014Model.FK_Technology_Thumbnail", "PortfolioImage").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<PortfolioImage> ThumbnailReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<PortfolioImage>("Plus54PortfolioRedesign2014Model.FK_Technology_Thumbnail", "PortfolioImage");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<PortfolioImage>("Plus54PortfolioRedesign2014Model.FK_Technology_Thumbnail", "PortfolioImage", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Plus54PortfolioRedesign2014Model", "FK_Project_Technologies", "Project")]
        public EntityCollection<Project> Projects
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Project>("Plus54PortfolioRedesign2014Model.FK_Project_Technologies", "Project");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Project>("Plus54PortfolioRedesign2014Model.FK_Project_Technologies", "Project", value);
                }
            }
        }

        #endregion

    }

    #endregion

}
