//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Plus54PortfolioRedesign2014.Resources.resources.global
{
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DatatablesTexts_res
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DatatablesTexts_res()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.resources.global.DatatablesTexts_res", typeof(DatatablesTexts_res).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Activate to sort column ascending.
        /// </summary>
        public static string AriaSortAscending
        {
            get
            {
                return ResourceManager.GetString("AriaSortAscending", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Activate to sort column descending.
        /// </summary>
        public static string AriaSortDescending
        {
            get
            {
                return ResourceManager.GetString("AriaSortDescending", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No data available in table.
        /// </summary>
        public static string EmptyTable
        {
            get
            {
                return ResourceManager.GetString("EmptyTable", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string InfoPostFix
        {
            get
            {
                return ResourceManager.GetString("InfoPostFix", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ,.
        /// </summary>
        public static string InfoThousandsDelimeter
        {
            get
            {
                return ResourceManager.GetString("InfoThousandsDelimeter", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Show _MENU_ entries.
        /// </summary>
        public static string LengthMenu
        {
            get
            {
                return ResourceManager.GetString("LengthMenu", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string LoadingRecords
        {
            get
            {
                return ResourceManager.GetString("LoadingRecords", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to First.
        /// </summary>
        public static string PaginateFirst
        {
            get
            {
                return ResourceManager.GetString("PaginateFirst", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Last.
        /// </summary>
        public static string PaginateLast
        {
            get
            {
                return ResourceManager.GetString("PaginateLast", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string PaginateNext
        {
            get
            {
                return ResourceManager.GetString("PaginateNext", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        public static string PaginatePrevious
        {
            get
            {
                return ResourceManager.GetString("PaginatePrevious", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Processing....
        /// </summary>
        public static string Processing
        {
            get
            {
                return ResourceManager.GetString("Processing", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Search:.
        /// </summary>
        public static string SearchLabel
        {
            get
            {
                return ResourceManager.GetString("SearchLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Showing _START_ to _END_ of _TOTAL_ entries.
        /// </summary>
        public static string ShowingInfo
        {
            get
            {
                return ResourceManager.GetString("ShowingInfo", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Showing 0 to 0 of 0 entries.
        /// </summary>
        public static string ShowingInfoEmpty
        {
            get
            {
                return ResourceManager.GetString("ShowingInfoEmpty", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to (filtered from _MAX_ total entries).
        /// </summary>
        public static string ShowingInfoFiltered
        {
            get
            {
                return ResourceManager.GetString("ShowingInfoFiltered", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No matching records found.
        /// </summary>
        public static string ZeroRecords
        {
            get
            {
                return ResourceManager.GetString("ZeroRecords", resourceCulture);
            }
        }
    }
}
